spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:8080/ssm?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml #指定主配置文件
  mapper-locations: classpath:/mybatis/mapper/*.xml # 指定xml映射文件路径
  type-aliases-package: com.atguigu.spring.bean # 指定mybatis别名包
logging:
  level:
    com.atguigu.spring: debug # 配置日志